### ISSUE TITLE
Add Command Line Options To Startup

### ISSUE THREAD

**Issue by paulhocker** [Sakrac/IceBroLite#22]
Hello. Just recently discovered your tool and it is a great help to some work I am doing. I was wondering if there any plans to have the ability to pass in symbol and debug files on the command line? Perhaps I missed it?

I am the author of this extension

https://gitlab.com/retro-coder/commodore/kick-assembler-vscode-ext

and it would be great to be able to add those as parameters when starting up the monitor.

Thanks.

**Comment by Sakrac** [comment]
added command line options, you can specify -load=program and -symbol=symbols or debug file. This only works when the debugger is launched though. The ideal way to work with the debugger is to launch it once, iterate on the program and reload the program many times without restarting VICE or the debugger, but this might help with launching the debugger for the first time in a debugging session! Can you compile this and test first or should I make a new release?
