### ISSUE TITLE
Code View Source Overlaps Dissambly

### ISSUE THREAD

**Issue by paulhocker** [Sakrac/IceBroLite#24]
Not a huge thing but sometimes, depending on the length of the symbols, overlapping will occur. This makes it more difficult to view when it is displayed. I did not see anyway to change the width. Thanks.

![image](https://user-images.githubusercontent.com/2214652/207140302-a5534c94-2757-43bd-ae68-9ba996b881c5.png)

**Comment by Sakrac** [comment]
I just tested clipping the disassembly if it overlaps but not if the source line is missing and that's an improvement!
