### ISSUE TITLE
Honor Window Size and Fullscreen Mode

### ISSUE THREAD

**Issue by paulhocker** [Sakrac/IceBroLite#25]
The current version does not honor the Window Size (main window) even if you save settings. It would also be great if it remembered if you ran it in full screen versus windowed.

Oh, and preferred theme as well. 

:)

I appreciate the other changes you made so quickly. Really nice.

**Comment by Sakrac** [comment]
Should work as expected now, don't worry about writing multiple issues, the theme is a bit different from the window properties :)

Don't worry, these things bug me too but I don't have the energy to fix them if I'm the only one using this :)

**Comment by paulhocker** [comment]
Almost there. Window size seems to work great along with theme but if I have the window maximized this is what i get when I reopen the app again. Thanks for fixing the other issues. 

![image](https://user-images.githubusercontent.com/2214652/208253805-10bed8d9-d41c-4f3f-bbf6-57cde4634e8a.png)

**Comment by paulhocker** [comment]
Found another weird thing. I can open another issue if you want to track separately.

Last theme is now saved and restored properly. However, if I change the font size at all, closing and reopening brings me back to the original theme again. 


https://user-images.githubusercontent.com/2214652/208253997-59f302d1-8c0d-460c-81a0-833212d3dbe2.mp4

**Comment by Sakrac** [comment]
Found the theme bug, turns out I saved the theme, loaded it but forgot to store which one so next time it saved it was the default one again! Fixed in code but not in a release.
The full screen issue I can't repro or maybe don't understand, does it not open the window maximized and the size is larger than the screen? Does double clicking the window bar maximize the window again? You can see what it is trying to restore if you open icebrolt.ini, it is just a text file.

**Comment by paulhocker** [comment]
Correct. It is not opening the window maximized. Instead, it seems to be opening in the size that is saved as when it was maximized, and then shifts it down and to the left. Almost like it is adjusting for the chrome around the windows. It could be a windows 11 thing too. If you exit the program with the screen maximized, does it open that way again for you?


https://user-images.githubusercontent.com/2214652/208270048-dd228620-48d5-4ae5-b232-45b4f6f4bea8.mp4

**Comment by Sakrac** [comment]
So it seems like the maximized state can not be guaranteed, works for me 100% BUT I'm making sure to save the window size before it gets maximized so at least it will open at the previous non-maximized size.

**Comment by paulhocker** [comment]
Working as I would expect now and also fixed the cursor size issue.
