### ISSUE TITLE
Not Using Windows Cursor Size

### ISSUE THREAD

**Issue by paulhocker** [Sakrac/IceBroLite#27]
As you can see in the video, I have my cursor set to be larger because I am using a high resolution screen. When I go inside the debugger window, it shrinks down to the default size for the screen resolution. It must ne a IMGUI thing probably?

Is there a setting to have it keep the cursor size as specified on the system?

thanks

https://user-images.githubusercontent.com/2214652/208263885-3964adaa-d801-4af3-a2ee-5ce4cbeecfac.mp4

**Comment by Sakrac** [comment]
Seems like a GLFW & ImGui issue, ImGui is mentioning this will be fixed in GLFW 3.4 but is at 3.37 right now. I can try just updating ImGui and see if that solves anything.

**Comment by Sakrac** [comment]
Fixed with latest version of GLFX / dear ImGui (v1.05)

**Comment by paulhocker** [comment]
Confirmed!
