### ISSUE TITLE
Displaying Binary or Decimal in Watch Window

### ISSUE THREAD

**Issue by paulhocker** [Sakrac/IceBroLite#28]
Maybe I am missing it in the Manual but I cannot figure out how to display a watch in Decimal or Binary?

It would also be cool to be able to right click on an address in the memory view or on the code window to automatically add it as a watch value.

**Comment by Sakrac** [comment]
Sounded easy but it was a bit more involved than I thought but should work now, just right click on the value of a watch and select how to show it.

Dragging from the symbol view or breakpoint view to the title of the watch view already works, but I don't have a drag source from disassembly or the memory view, you could add a new bug for that if you want.
