### ISSUE TITLE
Feature Request: Allow Upper/Lower Charset in Mem View

### ISSUE THREAD

**Issue by paulhocker** [Sakrac/IceBroLite#33]
Provide a toggle to let developer switch between upper/lower case in the Mem view. This will let us make sure that the correct petscii is getting added without having to resort to decoding it manually.

![image](https://user-images.githubusercontent.com/2214652/210148241-661ed931-d9e7-4f4d-bb7c-750207984b91.png)

**Comment by Sakrac** [comment]
added a flag for it in the memory view

**Comment by paulhocker** [comment]
The case setting is not working as I expected. I was hoping it would show the lowercase petscii values, instead it is showing question marks?


https://user-images.githubusercontent.com/2214652/210186181-6d33ffcc-3c7a-48f0-bccf-49195323c8c2.mp4

**Comment by Sakrac** [comment]
looks like I undid half of the fix! code has been fixed again!

**Comment by Sakrac** [comment]
This seems fixed in v1.12
