### ISSUE TITLE
Feature Request: Better Support for Non Commodore Fonts

### ISSUE THREAD

**Issue by paulhocker** [Sakrac/IceBroLite#34]
While the included C64 font is great from a nostalgic perspective, it is very difficult to work with from a coders perspective. I would be really great if we could use a different font like the IMGUI font while still being able to see the petscii values in the memory view. I realize this is a big ask, so I would be happy with just the ability to use a different font that I could use on my computer like Consolas, Hacker or some other coder font. Hope that made sense?

**Comment by Sakrac** [comment]
added a command line argument for -font=<full path>,<size in pixels>
if using the ImGui default font or a custom font then switch to closest pescii font for the memory view text portion

**Comment by paulhocker** [comment]
the font option works great, however it breaks the theme that you may have selected. maybe a theme option on the command line might solve this for you?

**Comment by Sakrac** [comment]
Looks like I accidentally deleted saving the style, this is fixed in code.

**Comment by Sakrac** [comment]
This seems fixed in v1.12
