### ISSUE TITLE
Dynamic disassembly

### ISSUE THREAD

**Issue by BacchusFLT** [Sakrac/IceBroLite#36]
The disassembly gives a static address that remains constant for the session, whereas I would like to have a disassembly that is around 1/3 before current PC and then 2/3 after the current PC.

You need to manually update it in case you want disassembly of the current position in the code. I have learned that you can do "=PC-12" to add a dynamic aspect, but a static number after the PC will mean that you can easily hit the middle of an instruction, and then the disassembly could very well be totally borked.

So I would look for a feature that provides a dynamic disassembly.

**Comment by Sakrac** [comment]
Added a trackPC checkbox to the code view, default to 1/3 of the disassembly but tries to keep the pc centered on the current line. It is a little bit jumpy due to valid half-instructions when stepping backwards so might try to improve it.

**Comment by BacchusFLT** [comment]
Great - looking forward to seeing it in action!

/Pontus Berg
 Bergatrollet AB
 CEO & Owner
 Tel/SMS: +46 735 082860
 www.bergatrollet.se


Den fre 6 jan. 2023 kl 13:40 skrev Carl-Henrik Skårstedt <
***@***.***>:

**Comment by Sakrac** [comment]
Track PC has been added as a checkbox in Code Views in the latest release (v1.12). It may require refinements but it is workable.
