### ISSUE TITLE
Action Replay - cheat

### ISSUE THREAD

**Issue by BacchusFLT** [Sakrac/IceBroLite#37]
In many ways, IceBro will work as a substitute to the freezer in cartridges and one feature that would be quite cool to see implemented in IceBro would be a "trainer hunter".

In Action Replay you freeze and select the option to hunt for trainers.
You enter the number of lives you currently have and then restart the game.
After you lose a life, you freeze again and select the option.

AR now looks for addresses that went from the initially entered value to one less. Then it will look for instructions that decreases it.

Here IceBro could also allow you to implement the trainer and resume or validate the trainer, by not implementing the trainer and instead resume and letting you lose another life and see if that made the game decrease properly.

**Comment by Sakrac** [comment]
Added a few commands to the console, pretty easy to extend in the future:
1. poke addr,byte
    addr and byte can be expressions so can use 'POKE \<symbol\>,\<symbol\>' or a basic 'POKE 53280,0'. Vice does not need to be in break mode to use this command.
2. remember \<byte\>[-\<byte\>] [\<addr\> \<addr\>] 
    'remember $03-$04 $300 $8000', finds and remembers all memory locations matching the byte range within the address range. can also just type 'remember 3', Vice does not need to be in break mode to use this command.
3. match \<byte\>[-\<byte\>] [\<addr\> \<addr\>] [T[RACE]] [W[ATCH]]
    finds matching byte values in the remembered set of addresses, optionally within a sub-range of addresses. Add a T or W at the end to automatically assign TracePoints or WatchPoints to the matches/ , Vice does not need to be in break mode to use this command.
5. forget (clears the remembered addresses)

**Comment by BacchusFLT** [comment]
Would need to test if it works of course before I say anything. I would
suggest having the options available via the console as suggested, but
possibly also using a more user friendly GUI option, similar to the one
Action Replay itself uses.

/Pontus Berg
 Bergatrollet AB
 CEO & Owner
 Tel/SMS: +46 735 082860
 www.bergatrollet.se


Den fre 6 jan. 2023 kl 13:38 skrev Carl-Henrik Skårstedt <
***@***.***>:

**Comment by Sakrac** [comment]
Commands have been added to the console view to handle this in the latest release (v1.12). For more details: https://sakrac.github.io/IceBroLite/ice_console.html
for additional improvements it is probably better to create new issues to make it easier to track.
