### ISSUE TITLE
Overhaul of the Graphics view

### ISSUE THREAD

**Issue by BacchusFLT** [Sakrac/IceBroLite#38]
The graphics view option "current" is logical, but the opportunity to view memory as graphics is IMHO calling for a bit of love. 

The input fields are only partically context aware;
If you chose multicolour as the option there is still a tickbox that allows you to tick/untick multicolour in the MC mode.  
A tick box for ROM font is visible also when you select any of the bitmap and sprite options - it's only valid in the Font context. 
If you select sprite or font, why would you want the input options for bitmap, $d800 and the rest?

The zoom option is not a parameter for graphics - that's a preference in the program.

**Comment by BacchusFLT** [comment]
A general panel that tells the current status would also be good. Current bank, hires/MC mode, char/bitmap mode, spritedata of enabled sprites and so on. And then the relevant references to bitmap/font, screen, sprite pointers, $d800 source and so on.

**Comment by Sakrac** [comment]
A pass has been done to the graphics view to address the suggestions, in the latest release (v1.12).
for additional improvements it is probably better to create new issues to make it easier to track.
