### ISSUE TITLE
Feature Request: Add Option to Hilite Current PC in Code View

### ISSUE THREAD

**Issue by paulhocker** [Sakrac/IceBroLite#39]
I have trouble sometimes finding where I am currently located in code view when the program is paused. It would be great to have an option to let me highlight the line I am currently on instead of the ">" that currently marks the line.

Keep in mind, once I start stepping through the code, it is not that big of a deal, but I do lose a few seconds searching for the ">" when it first breaks, so this is really more of a QOL feature request.

**Comment by Sakrac** [comment]
sounds good, would something like the box in the watch view be enough? (select an expression, press up/down), or would it be better with something like the purple highlight for the current breakpoint/edit instruction?

**Comment by Sakrac** [comment]
Added a customizable PC cursor for the code view, set the style in the Layout drop down menu (rectangle or solid, color).
You can try it in this build: https://github.com/Sakrac/IceBroLite/releases/tag/Nightly (I added a build so I can share features for testing before making full releases)

**Comment by paulhocker** [comment]
this looks great!

![image](https://user-images.githubusercontent.com/2214652/211426662-c7f61067-cc06-47f7-854f-720d6331531a.png)

**Comment by Sakrac** [comment]
Great! I'll make a full release when I have some more stuff.
