### ISSUE TITLE
Watch Panel Suppresses Values when using Custom Font

### ISSUE THREAD

**Issue by paulhocker** [Sakrac/IceBroLite#41]
Not sure if this was an existing bug with the new font option. It did also not work in the nightly build. It seems that when using a custom font, when you resize the Watch Panel, many of the values dissapear. The video included shows what it looks like when using the default font, versus the custom font.

It's interesting that it keep the visible values correct when first switching fonts, but then as soon as you change it they dissapear.

https://user-images.githubusercontent.com/2214652/222989096-086e29c4-297a-4109-8143-4c2e70262025.mp4

**Comment by Sakrac** [comment]
Fixed the character width calculation in the watch view, this is fixed in the Nightly build. Let me know if there are any other character width problems I have missed.

**Comment by paulhocker** [comment]
works perfectly -- have not seen any others yet

**Comment by Sakrac** [comment]
cool! fixed a couple of other minor problems and made a full release.
