### ISSUE TITLE
Please Add More Memory Panels

### ISSUE THREAD

**Issue by paulhocker** [Sakrac/IceBroLite#42]
I actually need more Memory Panels to view multiple blocks of memory. 2 more for sure, 4 would be even better.

:)

**Comment by Sakrac** [comment]
Eight memory views for you!

**Comment by paulhocker** [comment]
Thank you

![image](https://user-images.githubusercontent.com/2214652/226130340-fe2ba294-d5a8-4dfa-98a2-cf53ab0c04f9.png)
