### ISSUE TITLE
Feature Request: Reload Debugger Info Button

### ISSUE THREAD

**Issue by paulhocker** [Sakrac/IceBroLite#44]
In my workflow I continually leave IBL running in the background, and then run many iterations of VICE from VSCode. Part of that involves, reloading the latest and greatest debugger information from the assembler.

It would be great if there was a button to let me "reload" the last debugger file again. Saving me from having to go to the file menu, find the debugger file, and then select/load it.

Seems like a small thing, but I do it so many times that this would be a huge time saver for me.

There is a RELOAD button on IBL now, but I do not think it does what I am describing. I believe it only handles loading a single PRG file. In my project, I both load a cartridge and attach a disk image and then execute. Not something IBL can do today (I believe).

Let me know if you need a better description of what I am asking.

**Comment by Sakrac** [comment]
I was just thinking about adding that for myself, so I can rebuild the debugger and reconnect to VICE and get right back to the debug information. Should be pretty simple.
Technically I could attach multiple things, I just don't have a good way to set it up.

**Comment by Sakrac** [comment]
Added the button a a paths menu to review existing paths in case there is an issue with reloading symbols.
Release here: https://github.com/Sakrac/IceBroLite/releases/tag/v1.17

**Comment by paulhocker** [comment]
works nice, thanks!
