### ISSUE TITLE
Compile errors on Linux in both main branch and 1.17 tag

### ISSUE THREAD

**Issue by mstine** [Sakrac/IceBroLite#45]
I've followed the instructions at https://sakrac.github.io/IceBroLite/linux.html.

Attached logs from `STDOUT` and `STDERR` from running `make` in `IceBroLite/src`.

[make.log](https://github.com/Sakrac/IceBroLite/files/11335365/make.log)

**Comment by Sakrac** [comment]
Fixed, I forgot to use my cross platform define in that place. Please check it if you have a chance.

**Comment by mstine** [comment]
Works!
