### ISSUE TITLE
VICE executable selector is Windows only

### ISSUE THREAD

**Issue by musuruan** [Sakrac/IceBroLite#48]
I you try to load VICE from within ICeBroLIce (File -> Load VICE), the file selector is "x*.exe" which is only valid under Windows. For example, under Linux the VICE binaries do not have ".exe" extension.

**Comment by Sakrac** [comment]
Changed it to accept specific filenames without .exe for non-windows. I don't have linux or mac set up at home right now so can't test it, test it if you have a chance

**Comment by musuruan** [comment]
It works.

![immagine](https://github.com/Sakrac/IceBroLite/assets/1221995/a7b61ee0-bf20-4681-adee-3b3b913d914f)
