### ISSUE TITLE
Open Multiple .dbg Files

### ISSUE THREAD

**Issue by paulhocker** [Sakrac/IceBroLite#55]
I have a use case where I would like to open two (or more) separate .dbg files.

The is needed because I have one main cartridge which can open and run a different program(s) from disk.

I have one .dbg file for the main cart build, and then I have a separate .dbg file for the different programs it can load.

Today I have to load one or the other. Not a deal breaker but being able to open more than one .dbg would be a great quality of life thing for me.

Perhaps this feature is already there and I missed it because the icebrolt.ini has a section called "Filenames"

Filenames {
  DebugData = C:\Users\paul\Workspace\retro-coder\animal-shell\bin\128\dir.dbg
}

**Comment by Sakrac** [comment]
It isn't something that works right now, Filenames just means global filenames for specific things. RIght now I clear the symbols when a new debug data is loaded but I think it would be fine to load another one. I\ll see what the best way to support it is. Do you think it will be limited to one main debug data and one additional?

**Comment by paulhocker** [comment]
Adding the ability for an additional file would be brilliant. That way I can load my cartridge debug file, and then one additional file that is loaded. Cheers.

**Comment by Sakrac** [comment]
You can check out this release: https://github.com/Sakrac/IceBroLite/releases/tag/v1.20
there is both a menu option under File and a command line option -extradebug=other.dbg
let me know if it works and I can set it to a full release

**Comment by paulhocker** [comment]
This seems to work very well. However, it seems that if I press the RELOAD DEBUG INFO button that only the first "main" debug information is reloaded and the secondary appears to be wiped out.

https://github.com/user-attachments/assets/90fdb093-0a2b-4142-97c2-82d737f0158b

**Comment by Sakrac** [comment]
Yes, I don't have another way of unloading the additional debug data any other way, but I agree it feels wrong if you specify the extra debug data on the command line. I'll think about it some more.

**Comment by Sakrac** [comment]
Ok, I reload the extra debug data if you specify it on the command line but not if loading it from the menu which should make sense in both cases. I've updated the files in version 1.20 and marked it as a full release!
